name: Deploy to staging

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js and yarn
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install --frozen-lockfile

      - name: Generate env from secrets
        run: |
          SECRETS="${{ secrets.CHATAPP_GCP_ENV_STAGING }}"
          echo "$SECRETS" | tr ';' '\n' >> .env

      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.CHATAPP_GCP_SA_KEY }}"
          project_id: ${{ secrets.CHATAPP_GCP_PROJECT_ID }}

      - name: Set up Cloud SDK
        uses: "google-github-actions/setup-gcloud@v2"

      - name: Deploy to Google App Engine
        run: |
          gcloud app deploy app.yaml --quiet